### PR TITLE
base:add_centos7_builds

### PR DESCRIPTION
**Pull request by Mahgadgi**
support_testing/nginx_container farm_github_action

### CODE REVIEW

**Comment by Mahgadgi** [comment]
dependabot/npm_and_yarn/server/lodash-4.17.21

**Comment by phracek** [comment]
@Mahgadgi Can you please rebase it on the top of the master? 31 commits? I don't follow.

**Comment by Mahgadgi** [comment]
> @Mahgadgi Can you please rebase it on the top of the master? 31 commits? I don't follow.

O

> @Mahgadgi Can you please rebase it on the top of the master? 31 commits? I don't follow.

Ok@phracek let me rebase it

**Review by Mahgadgi — COMMENTED** [review]
I had it rebased so that you can follow https://github.com/sclorg/nginx-container/pull/180#issue-1165140902

**Comment by pkubatrh** [comment]
"wants to merge 31 commits into [add_centos7_builds]" - from master into a differnt branch? I do not follow what this PR is wanting to achieve.

**Review by Mahgadgi — COMMENTED** [review]
1.20/Dockerfile.c9s

**Comment by phracek** [comment]
@Mahgadgi I would prefer these steps:

```bash
$ git checkout master
$ git fetch --all
$ git checkout add_centos7_builds
$ git rebase -i master
```
As soon as you have rebased it, then we can see your changes.

**Comment by phracek** [comment]
There is no well-written description. Also, the name of the pull request is weird. Closing this issue.

**Pull request closed without merging**
