### PR TITLE
move test_latest_imagestreams case into openshift tests

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Review by phracek — COMMENTED** [review]
Thanks for the PR! Imagestream tests are relevant only for OpenShift part. As soon as tests are passing. We can merge it.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Review by phracek — COMMENTED** [review]
LGTM. Thanks for the fix. As soon as tests are green we can merge it.

**Review by phracek — APPROVED** [review]

**Pull request merged**
