### PR TITLE
Enable building nginx 1.20 image for RHEL 8

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
Note that Openshift 3 test likely fails due to "The latest version is not present in imagestreams/nginx-rhel.json or in latest tag." rather than failing to clean up.

**Comment by zmiklank** [comment]
In RHEL8 test logs can be seen that the build of RHEL8 with nginx 1.20 was successfully started (and also finished).

**Comment by pkubatrh** [comment]
That is because for remote Openshift tests the imagestream test is actually commented out: https://github.com/sclorg/nginx-container/blob/master/test/run-openshift-remote-cluster#L32

**Comment by zmiklank** [comment]
Rebased on master.

**Comment by zmiklank** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-all]

**Comment by pkubatrh** [comment]
LGTM thanks!

**Pull request merged**
