### PR TITLE
Add missing imagestreams for Nginx-1.24

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Comment by phracek** [comment]
> Do you need this to be merged ASAP? I would like to use imagestream generator for this too, but it may take a while. If you need this change now, we can merge this, and do the imagestream generator in the future. WDYT?
> 
> Please note, I did not review this yet.

We can use imagestream generator. We should have new imagestreams definitely during the middle of April for sure.

**Comment by phracek** [comment]
Nightly builds are failing. It would be nice to merge it, even though we will have imagestreams generated by imagestream-generator.

[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
There is problem with the GitHub Action for checking the imagestreams that I added. I will address that in separate PR. Meanwhile this LGTM.

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
