### PR TITLE
Enable SCL in the Dockerfile already

### PR DESCRIPTION
**Pull request by hhorak**
In order to make the nginx binary be available in the Dockerfile or in the corner cases, this PR enables the SCL already using the ENV statements. This should be pretty safe way to do it since SCL enable scriptlets do not change often, usually at all.

✅ This PR requires https://github.com/sclorg/container-common-scripts/pull/179 be merged first.

This is also a preparation work for being able to use the nginx container easier using a Dockerfile, similarly to https://github.com/sclorg/httpd-container/pull/99.

The tests did not work properly in all environments (e.g. podman without root access), so some minor changes were done in the test script. In order to avoid unnecessary code duplication (test scripts in recent `$VERSION/test` directories were exactly the same), the test script was moved to a common directory and particular scripts in `$VERSION/test` directories are symlinks now.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
This is weird, the last commit in https://github.com/hhorak/nginx-container/commit/eb4a19c386f40729b19a46c996b9c37b760bc48e with hash eb4a19c3 is not visible in this PR. What's going on?

**Comment by hhorak** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. Thanks for the PR.

**Comment by pkubatrh** [comment]
[test-openshift]

**Pull request merged**
