### PR TITLE
Add 1.22 version

### PR DESCRIPTION
**Pull request by hhorak**
Only Fedora is available at the moment, so other OS's are ignored now.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Review by phracek — CHANGES_REQUESTED** [review]
The changes look good, but you forgot to add the version into Makefile. Please update also main README.md file.

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
@hhorak Fedora test has failed on the last test `[FAILED] run_dockerfiles_test`:

```bash
 ---> f7f5b2ceefdd
Step 3/7 : ADD nginx-container/examples/1.22/test-app/nginx.conf "${NGINX_CONF_PATH}"
ADD failed: file not found in build context or excluded by .dockerignore: stat nginx-container/examples/1.22/test-app/nginx.conf: file does not exist
ERROR: The image cannot be built from /tmp/tmp.BizvHzZqvf and application https://github.com/sclorg/nginx-container.git.
Terminating the Dockerfile build.
```

**Pull request merged**
