### PR TITLE
Support testing imagestreams on RHEL9

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for testing imagestreams also on RHEL9

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
RHEL9 images stream test has passed
```bash
-----------------------------------------------
Running test test_nginx_imagestream (starting at 2022-10-14 09:22:43+02:00) ... 
-----------------------------------------------
Running image stream test for stream test/imagestreams/nginx-rhel.json and application https://github.com/sclorg/nginx-container.git with context examples/1.20/test-app
Now using project "sclorg-test-23233" on server "https://api.core-serv-ocp.hosted.psi.rdu2.redhat.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.
[snipped]
Waiting for command POD .NAME                                 READY   STATUS              RESTARTS   AGE
command-app                          0/1     ContainerCreating   0          <invalid>
nginx-120-testing-1-build            0/1     Completed           0          27s
nginx-120-testing-749cb64d84-vnbjv   1/1     Running             0          5s
.NAME                                 READY   STATUS              RESTARTS   AGE
command-app                          0/1     ContainerCreating   0          <invalid>
nginx-120-testing-1-build            0/1     Completed           0          31s
nginx-120-testing-749cb64d84-vnbjv   1/1     Running             0          9s
DONE
Error from server (NotFound): deploymentconfigs.apps.openshift.io "nginx-120-testing" not found
  Information about the image we work with:
Error from server (NotFound): deploymentconfigs.apps.openshift.io "nginx-120-testing" not found
error: resource name may not be empty
error: resource name may not be empty
  Check passed.
Deleting project skipped, cleaning objects only.
```

**Comment by hhorak** [comment]
[test-all]

**Comment by phracek** [comment]
@hhorak Everything look good, in case you get Approved or LGTM, I will merge it.

**Comment by phracek** [comment]
[test-all]

**Comment by hhorak** [comment]
LGTM, thanks.

**Pull request merged**
