### PR TITLE
Fix calling each testsuite and catch result

### PR DESCRIPTION
**Pull request by phracek**
This commit fixes the catching result of each function.
If the testcase does not exist, then failure is caught.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@fila43 Please take a look at it. Thanks.

**Comment by phracek** [comment]
@pkubatrh If you have time, please take a look at it. Thanks.

**Comment by fila43** [comment]
Looks fine, LGTM

**Pull request merged**
