### PR TITLE
Fix symlink to examples

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds an examples symlink into the test directory.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by pkubatrh** [comment]
lgtm, thanks!

Lets merge after tests pass

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Test on RHEL-7 failed with reason
```bash
No package rh-nginx116 available.
No package rh-nginx116-nginx available.
No package rh-nginx116-nginx-mod-stream available.
No package rh-nginx116-nginx-mod-http-perl available.
```
It looks like repository does not contain the package

**Comment by phracek** [comment]
Repos which are used for building are:

```bash
rhel-7-server-rpms rhel-7-server-optional-rpms rhel-server-rhscl-7-rpms
```
which is correct.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
I have tested to run PR test here: https://github.com/sclorg/s2i-php-container/pull/320

```bash
08:09:31 + yum-config-manager --enable rhel-7-server-rpms rhel-7-server-optional-rpms rhel-server-rhscl-7-rpms
[..snip..]
08:09:39 Error: Package: rh-php73-php-cli-7.3.20-1.el7.x86_64 (ubi-server-rhscl-7-rpms)
08:09:39            Requires: libpcre2-8.so.0()(64bit)
08:09:39 Error: Package: rh-php73-php-7.3.20-1.el7.x86_64 (ubi-server-rhscl-7-rpms)
08:09:39            Requires: libpcre2-8.so.0()(64bit)
08:09:39 Error: Package: rh-php73-php-cli-7.3.20-1.el7.x86_64 (ubi-server-rhscl-7-rpms)
08:09:39            Requires: libpcre2-8.so.0()(64bit)
08:09:39 Error: Package: rh-php73-php-7.3.20-1.el7.x86_64 (ubi-server-rhscl-7-rpms)
08:09:39            Requires: libpcre2-8.so.0()(64bit)
08:09:39 **********************************************************************
08:09:39 yum can be configured to try to resolve such errors by temporarily enabling
08:09:39 disabled repos and searching for missing dependencies.
08:09:39 To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
08:09:39 **********************************************************************
08:09:39 
08:09:39  You could try using --skip-broken to work around the problem
08:09:39  You could try running: rpm -Va --nofiles --nodigest
08:09:39 The command '/bin/sh -c yum install -y yum-utils &&     prepare-yum-repositories rhel-server-rhscl-7-rpms &&     INSTALL_PKGS="rh-php73 rh-php73-php rh-php73-php-mysqlnd rh-php73-php-pgsql rh-php73-php-bcmath                   rh-php73-php-gd rh-php73-php-intl rh-php73-php-ldap rh-php73-php-mbstring rh-php73-php-pdo                   rh-php73-php-process rh-php73-php-soap rh-php73-php-opcache rh-php73-php-xml                   rh-php73-php-gmp rh-php73-php-pecl-apcu httpd24-mod_ssl" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*'' returned a non-zero code: 1
```

It looks like there is a infrastructure problem. `ubi-server-rhscl-7-rpms` repository we did not set anywhere AFAIK.

**Comment by pkubatrh** [comment]
```
sudo docker run --rm -ti ubi7 bash -c "cat /etc/yum.repos.d/ubi.repo | grep rhscl"
[ubi-server-rhscl-7-rpms]
baseurl = https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/$basearch/rhscl/1/os
[ubi-server-rhscl-7-debug-rpms]
baseurl = https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/$basearch/rhscl/1/debug
[ubi-server-rhscl-7-source-rpms]
baseurl = https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/$basearch/rhscl/1/source/SRPMS
```

The problem is that this repository is used at all, pointing to the fact that the rhscl repositories inside the image are unavailable.

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Test is failing, because new slaves are not built yet ;)

**Comment by phracek** [comment]
[test]

**Pull request merged**
