### PR TITLE
Adds check for the latest version in imagestreams

### PR DESCRIPTION
**Pull request by phracek**
This commit adds the check if latest version in present in imagestreams.

### CODE REVIEW

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
Failure is expected. Waiting for merge https://github.com/sclorg/container-common-scripts/pull/157

**Comment by hhorak** [comment]
Merged now.

**Comment by phracek** [comment]
Fedora failed on the infrastructure problem. Rerunning tests again.

[test][test-openshift]

**Comment by hhorak** [comment]
LGTM, thanks!

**Pull request merged**
