### PR TITLE
Support nginx 1.24

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building, and testing the nginx-container with version 1.24.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
I have tested Nginx-container 1.24 on Fedora locally and results are:

```bash
==============================================
Tests were run for image quay.io/fedora/nginx-124:0
==============================================
Test cases results:

 [PASSED] for 'test-app' test_s2i_usage (00:00:00)
 [PASSED] for 'test-app' test_docker_run_usage (00:00:01)
 [PASSED] for 'test-app' test_application (00:00:03)
 [PASSED] for 'test-app' test_log_output (00:00:02)
 [PASSED] for 'test-app' test_log_volume_output (00:00:02)
 [PASSED] for 'test-app' test_application_user (00:00:02)
 [PASSED] for 'start-hook-test-app' test_pre_init_script (00:00:03)
 [PASSED] for 'miscellaneous-tests' run_dockerfiles_test (00:00:20)

Tests for quay.io/fedora/nginx-124:0 succeeded.
```

Let's try it in CI

[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
Why are you adding new files under 1.22/ directory?

**Comment by phracek** [comment]
> Why are you adding new files under 1.22/ directory?

See https://github.com/sclorg/welcome/blob/master/contribution.md#2-add-sources.

First of all move sources from 1.22 -> 1.24 and then copy them back to 1.22 and fix 1.24 versions in 1.24 directory.

**Review by zmiklank — APPROVED** [review]
Thank you, lgtm.

**Pull request merged**
