### PR TITLE
Enable 1.18 version

### PR DESCRIPTION
**Pull request by pkubatrh**
start building rhel-based 1.18 versions
move nginx-118 images to UBI
~~try building nginx-118 for centos7 as well~~ centos7 rpm builds not available yet

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Review by phracek — APPROVED** [review]
LGTM. Thanks for the PR! As soon as tests are passing, let's merge it.

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
LGTM
[test]

**Comment by phracek** [comment]
Problem in RHEL8

```bash
STEP 3: ADD nginx-container/examples/$NGINX_VERSION/test-app/nginx.conf "${NGINX_CONF_PATH}"
Error: error dry-running "ADD nginx-container/examples/$NGINX_VERSION/test-app/nginx.conf \"${NGINX_CONF_PATH}\"": no files found matching "/tmp/tmp.kATrgJ7WpB/nginx-container/examples/test-app/nginx.conf": no such file or directory
ERROR: The image cannot be built from ../examples/Dockerfile and application https://github.com/sclorg/nginx-container.git.
Terminating the Dockerfile build.
```

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
> Problem in RHEL8

This should be fixed with https://github.com/sclorg/nginx-container/pull/139, let's see tests results again.

**Comment by pkubatrh** [comment]
Rebased for #139 

[test]

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Pull request merged**
