### PR TITLE
Remove RHEL-7 support - EOL June 2024

### PR DESCRIPTION
**Pull request by phracek**
This pull request removes RHEL-7 from this repository.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Fedora failures are expected and should be fixed by #297

**Comment by phracek** [comment]
The grep over this repository for 'rhel7' is:
```
$ grep -rn 'rhel7' *
1.20/Dockerfile.rhel7:1:FROM rhscl/s2i-core-rhel7:1
1.20/Dockerfile.rhel7:39:      name="rhscl/${NAME}-${NGINX_SHORT_VER}-rhel7" \
1.20/Dockerfile.rhel7:44:      usage="s2i build <SOURCE-REPOSITORY> rhscl/${NAME}-${NGINX_SHORT_VER}-rhel7:latest <APP-NAME>"
```

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-all]

**Review by jplesnik — APPROVED** [review]

**Pull request merged**
