### PR TITLE
Version 1.22/test directory did not contain symlinks like the others

### PR DESCRIPTION
**Pull request by phracek**
Version 1.22/test directory did not contain symlinks like the others
This pull request fixes symlinks in 1.22/test directory

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by zmiklank** [comment]
Hm, this is happening way too often. Do you think we could enforce some rules/checks for this? Or maybe use distgen everywhere ;).

**Review by zmiklank — APPROVED** [review]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
> Hm, this is happening way too often. Do you think we could enforce some rules/checks for this? Or maybe use distgen everywhere ;).

No please no dist-gen :(

**Pull request merged**
