### PR TITLE
Enable building and testing Nginx-1.22 on RHEL8

### PR DESCRIPTION
**Pull request by phracek**
This pull request enables building and testing Nginx-1.22 container on RHEL8

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
RHEL8 failures are caused by the error from the our tests:

```bash
$ docker run --user=10001 ubi8/nginx-122-micro:1-test-app
ls: cannot open directory '/var/log/nginx': Permission denied
$
```

It looks like it failed here: https://github.com/sclorg/nginx-container/blob/master/1.22/s2i/bin/run#L12

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
@hhorak @zmiklank Nginx-1.22-micro image is fixed by commit https://github.com/sclorg/nginx-container/pull/233/commits/1ded93ed4579f3552b97d80ecb5f9f2953e20969 I would be glad for your review and if permissions are properly set, like for 1.22/Dockerfile.rhel8.

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
OpenSHift 4 is locally passing:

```bash
project.project.openshift.io "sclorg-test-4709" deleted
Project sclorg-test-4709 was deleted properly
 [PASSED] for 'openshift-remote-cluster' test_nginx_integration (00:01:42)
 [PASSED] for 'openshift-remote-cluster' test_nginx_imagestream (00:01:53)

OpenShift tests for ubi8/nginx-122-micro:1 succeeded.
```

**Comment by phracek** [comment]
[test-all]

**Comment by hhorak** [comment]
> @hhorak @zmiklank Nginx-1.22-micro image is fixed by commit [1ded93e](https://github.com/sclorg/nginx-container/commit/1ded93ed4579f3552b97d80ecb5f9f2953e20969) I would be glad for your review and if permissions are properly set, like for 1.22/Dockerfile.rhel8.

I've added another commit [f66d7d8](https://github.com/sclorg/nginx-container/pull/233/commits/f66d7d83bffd9b6a78eaa61e0af0a5628a896691) that synchronizes what fedora and rhel-8 dockerfiles do around chmod/chown.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
New compose is used for testing image under RHEL-7.

[test-all]

**Comment by phracek** [comment]
Fedora issue should be fixed by #237

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by hhorak** [comment]
This lgtm, I'm just not sure if the ocp4 failures are expected, so not merging so far, but feel free to if you know why it is and it's expected.

**Comment by phracek** [comment]
[test-openshift]

**Pull request merged**
