### PR TITLE
automatically update image description to quay.io

### PR DESCRIPTION
**Pull request by zmiklank**
Depends on: https://github.com/sclorg/build-and-push-action/pull/34

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test]

**Review by phracek — APPROVED** [review]

**Pull request merged**
