### PR TITLE
Update imagestreams for RHSCL 3.6

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
@yselkowitz nginx-118 is also a UBI so we can add it to the community imagestream file as well. What do you think? If you're busy, I can prepare the update in a separate PR.

**Comment by hhorak** [comment]
Otherwise LGTM for the RHEL imagestream.

**Comment by yselkowitz** [comment]
It was only added to UBI8, not UBI7.  This is still within the RHSCL namespace, and last I checked there hadn't been a CentOS build to match.

**Comment by yselkowitz** [comment]
Oh, you're right, they did add it to UBI7 after all.  I can fix that.

**Comment by yselkowitz** [comment]
Repushed with UBI7 for both OKD and OCP imagestreams.

**Comment by hhorak** [comment]
Yeah, there was an issue that nodejs14 and nginx118 packages were missing in UBI7 repos, but it's fixed now.

**Comment by hhorak** [comment]
Thanks.

**Comment by hhorak** [comment]
[test][test-openshift][test-openshift-4]

**Comment by hhorak** [comment]
The tests are somehow broken, so I've verified this manually with OCP 4.6, looks good, merging.

**Pull request merged**
