### PR TITLE
Using OC_ERR variable for OC failures

### PR DESCRIPTION
**Pull request by zmiklank**
This would need a support in container-common-scripts.

### CODE REVIEW

**Comment by zmiklank** [comment]
Blocked on https://github.com/sclorg/container-common-scripts/pull/298.

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
Let's try it one more time. In case of 'Infra problems' for RHEL7 and RHEL8, let's file the problem to TF team.

[test-all]

**Comment by zmiklank** [comment]
[test-all]

**Comment by zmiklank** [comment]
TF is now green.
[test-all]

**Pull request merged**
