### PR TITLE
Use nss_wrapper-libs only to get rid of perl

### PR DESCRIPTION
**Pull request by hhorak**
This is not possible in RHEL8 yet unfortunately, as there is no `nss_wrapper-libs` package available.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
> This is not possible in RHEL8 yet unfortunately, as there is no `nss_wrapper-libs` package available.

@hhorak I don't follow, `nss_wrapper-libs` is not available in RHEL8 but you modified Dockerfile.fedora?
Is it intended?

**Review by phracek — APPROVED** [review]
LGTM

**Pull request merged**
