### PR TITLE
Remove streams that will be soon EOL.

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
@yselkowitz @phracek @pkubatrh WDYT?

**Comment by yselkowitz** [comment]
LGTM, but any explanation for the test failures?

**Comment by hhorak** [comment]
We still didn't convince Jenkins to work properly, so I verified manually that the imagestream is valid. Merging.

**Pull request merged**
