### PR TITLE
Imagestream files generated by imagestream generator

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
Depends on: https://github.com/sclorg/ci-scripts/pull/120

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
RHEL8 and RHEL9 OpenShift 4 tests are fixed by #284

**Comment by phracek** [comment]
Let's get merge it.

**Review by phracek — APPROVED** [review]

**Pull request merged**
