### PR TITLE
Use --chown option for ADD when adding app source instead of changing USER

### PR DESCRIPTION
**Pull request by hhorak**
I found this `--chown` option of `ADD` statement in the Dockerfile today, it seems like much better way to set correct permissions to make the assemble script work.

### CODE REVIEW

**Comment by hhorak** [comment]
Hm, it seems to not work with `docker` :(

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
Similar PR to https://github.com/sclorg/s2i-python-container/pull/422.

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test]

**Comment by pkubatrh** [comment]
lgtm, thanks!

**Pull request merged**
