### PR TITLE
Fixes #194: Do not build CentOS Stream 8 into quay.io.

### LINKED ISSUE #194: CentOS Stream 8 should be deprecated
CentOS Stream 8 should be deprecated because we have UBI image.

### PR DESCRIPTION
**Pull request by phracek**
Do not build CentOS Stream 8 into quay.io.

Container tests and OpenShift tests are still present

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
@pkubatrh Question is if we want to also test the image for CentOS Stream 8 or remove CentOS Stream 8 completely.

**Comment by pkubatrh** [comment]
I do not think we need to test it if we do not provide it at all.

**Comment by phracek** [comment]
I have removed CentOS Stream 8 completely. Including Dockerfile.c8s

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Pull request merged**
