### PR TITLE
Fix issue #96

### PR DESCRIPTION
**Pull request by Richard-Degenne**

### CODE REVIEW

**Comment by jemerald** [comment]
Could you update other versions too?

**Comment by Richard-Degenne** [comment]
I've updated versions `1.10` through `1.20`. I took a look at versions `1.6` and `1.8` but I don't think the issue is applicable there.

**Comment by zmiklank** [comment]
[test-all]

**Review by phracek — APPROVED** [review]
LGTM, Although only 1.18 and 1.20 are supported.

**Pull request merged**
